export const preferenceCopy = {
  es: {
    introHighlight: "Desarrollador Full Stack",
    introRest:
      " especializado en la creación de sistemas digitales, plataformas administrativas y aplicaciones web y móviles. Cuento con experiencia en el análisis, diseño, desarrollo, despliegue y optimización de soluciones funcionales, escalables y bien estructuradas, utilizando distintas herramientas y tecnologías para resolver problemas técnicos y participar en todo el ciclo de desarrollo de software.",
    profileAlt: "Foto de perfil de Ricardo Nava",
    profileHint: "Presiona aquí",
    openProfileLabel: "Abrir panel de perfil",
    closeProfileLabel: "Cerrar panel de perfil",
    profileMenuTitle: "Perfil",
    profileEmail: "lic.ricardo.nm@gmail.com",
    profileLocation: "México",
    profileFocusTitle: "Áreas de enfoque",
    focusMobile: "Aplicaciones móviles",
    linkedinLabel: "Abrir perfil de LinkedIn",
    githubLabel: "Abrir perfil de GitHub",
    githubActivityTitle: "Actividad de GitHub",
    githubActivityLoading: "Cargando actividad...",
    githubActivityError: "No se pudo cargar la actividad.",
    githubActivityLess: "Menos",
    githubActivityMore: "Más",
    githubAchievementsLabel: "Logros",
    githubFollowerLabel: "Seguidor",
    githubRepositoriesLabel: "Repositorios",
    githubViewProfileLabel: "Ver perfil",
    githubProfileSummaryLabel: "Resumen de perfil de GitHub",
    skillsTitle: "Habilidades y Tecnologías",
    projectsRouteTitle: "Proyectos",
    projectsSubtitle:
      "Selección de proyectos destacados, productos digitales y soluciones que he desarrollado.",
    technologiesSubtitle:
      "Tecnologías, lenguajes y herramientas que utilizo para desarrollar soluciones web y aplicaciones completas.",
    activitySubtitle:
      "Resumen visual de mis contribuciones en GitHub durante el último año.",
    contactSubtitle: "Enviame un mensaje directo.",
    contactFullNameLabel: "Nombre completo",
    contactFullNamePlaceholder: "Ingresa tu nombre",
    contactEmailLabel: "Correo electrónico",
    contactEmailPlaceholder: "correo@ejemplo.com",
    contactMessageLabel: "Mensaje",
    contactMessagePlaceholder: "Escribe tu mensaje...",
    contactMessageCounterLabel: "caracteres",
    contactUnsafeMessage:
      "El mensaje contiene contenido no permitido. Retiralo para continuar.",
    contactSendLabel: "Enviar",
    contactSendingLabel: "Enviando...",
    contactSuccessTitle: "Mensaje enviado",
    contactSuccessDescription: "Tu mensaje se ha enviado con exito.",
    contactErrorMessage: "No se pudo enviar el mensaje. Intentalo de nuevo.",
    contactLeaveTitle: "¿Deseas salir y borrar el contenido?",
    contactLeaveDescription:
      "Tienes información escrita en el formulario. Si sales ahora, se perderá.",
    contactStayLabel: "No salir",
    contactLeaveLabel: "Salir",
    aboutTitle: "Acerca de mí",
    resumeLabel: "Descargar CV",
    breadcrumbLabel: "Ruta de navegacion",
    homeNavLabel: "Navegación principal",
    homeRouteLabel: "Ir al inicio",
    drawerNavigationTitle: "Navegación",
    experienceRouteTitle: "Experiencia laboral",
    achievementsRouteTitle: "Logros destacados",
    projectsNavLabel: "Ver proyectos",
    technologiesRouteTitle: "Habilidades y Tecnologías",
    activityRouteTitle: "Actividad de GitHub",
    contactRouteTitle: "Contacto",
    experienceNavLabel: "Ver experiencia laboral",
    achievementsNavLabel: "Ver logros destacados",
    technologiesNavLabel: "Ver habilidades y tecnologías",
    activityNavLabel: "Ver actividad de GitHub",
    contactNavLabel: "Ver contacto",
    preferencesLabel: "Preferencias del sitio",
    openSettingsLabel: "Abrir preferencias",
    closeSettingsLabel: "Cerrar preferencias",
    languageLabel: "Cambiar idioma a inglés",
    languageText: "ES",
    lightThemeLabel: "Cambiar a tema oscuro",
    darkThemeLabel: "Cambiar a tema claro",
    lightThemeText: "Claro",
    darkThemeText: "Oscuro",
  },
  en: {
    introHighlight: "Full Stack Developer",
    introRest:
      " specialized in building digital systems, administrative platforms, and web and mobile applications. I have experience in the analysis, design, development, deployment, and optimization of functional, scalable, and well-structured solutions, using different tools and technologies to solve technical problems and participate in the full software development lifecycle.",
    profileAlt: "Ricardo Nava profile photo",
    profileHint: "Press here",
    openProfileLabel: "Open profile panel",
    closeProfileLabel: "Close profile panel",
    profileMenuTitle: "Profile",
    profileEmail: "lic.ricardo.nm@gmail.com",
    profileLocation: "Mexico",
    linkedinLabel: "Open LinkedIn profile",
    githubLabel: "Open GitHub profile",
    githubActivityTitle: "GitHub activity",
    githubActivityLoading: "Loading activity...",
    githubActivityError: "Activity could not be loaded.",
    githubActivityLess: "Less",
    githubActivityMore: "More",
    githubAchievementsLabel: "Achievements",
    githubFollowerLabel: "Follower",
    githubRepositoriesLabel: "Repositories",
    githubViewProfileLabel: "View profile",
    githubProfileSummaryLabel: "GitHub profile summary",
    skillsTitle: "Skills and Technologies",
    projectsRouteTitle: "Projects",
    projectsSubtitle:
      "Selected projects, digital products, and solutions I have developed.",
    technologiesSubtitle:
      "Technologies, languages, and tools I use to develop complete web solutions and applications.",
    activitySubtitle:
      "Visual summary of my GitHub contributions over the past year.",
    contactSubtitle: "Send me a direct message.",
    contactFullNameLabel: "Full name",
    contactFullNamePlaceholder: "Enter your name",
    contactEmailLabel: "Email",
    contactEmailPlaceholder: "email@example.com",
    contactMessageLabel: "Message",
    contactMessagePlaceholder: "Write your message...",
    contactMessageCounterLabel: "characters",
    contactUnsafeMessage:
      "The message contains unsupported content. Remove it to continue.",
    contactSendLabel: "Send",
    contactSendingLabel: "Sending...",
    contactSuccessTitle: "Message sent",
    contactSuccessDescription: "Your message has been sent successfully.",
    contactErrorMessage: "The message could not be sent. Please try again.",
    contactLeaveTitle: "Leave and discard this content?",
    contactLeaveDescription:
      "You have information written in the form. If you leave now, it will be lost.",
    contactStayLabel: "Stay",
    contactLeaveLabel: "Leave",
    aboutTitle: "About me",
    resumeLabel: "Download resume",
    breadcrumbLabel: "Breadcrumb",
    homeNavLabel: "Main navigation",
    homeRouteLabel: "Go home",
    drawerNavigationTitle: "Navigation",
    experienceRouteTitle: "Work experience",
    achievementsRouteTitle: "Featured achievements",
    projectsNavLabel: "View projects",
    technologiesRouteTitle: "Skills and Technologies",
    activityRouteTitle: "GitHub activity",
    contactRouteTitle: "Contact",
    experienceNavLabel: "View work experience",
    achievementsNavLabel: "View featured achievements",
    technologiesNavLabel: "View skills and technologies",
    activityNavLabel: "View GitHub activity",
    contactNavLabel: "View contact",
    preferencesLabel: "Site preferences",
    openSettingsLabel: "Open preferences",
    closeSettingsLabel: "Close preferences",
    languageLabel: "Switch language to Spanish",
    languageText: "EN",
    lightThemeLabel: "Switch to dark theme",
    darkThemeLabel: "Switch to light theme",
    lightThemeText: "Light",
    darkThemeText: "Dark",
  },
} as const;

export type PreferenceLabels =
  (typeof preferenceCopy)[keyof typeof preferenceCopy];
